### PR TITLE
add Get/Post method

### PR DESCRIPTION
**Pull request by pouriya73**
Co-authored-by: Pouriya nlp.developer.c@gmail.com

### CODE REVIEW

**Comment by MacWill20** [comment]
Co-authored-by: Pouriya nlp.developer.c@gmail.com

**Comment by pouriya73** [comment]
we need this const on HTTP - TCC 
const (
	// StateNew represents a new connection that is expected to
	// send a request immediately. Connections begin at this
	// state and then transition to either StateActive or
	// StateClosed.
	StateNew [ConnState](https://pkg.go.dev/net/http#ConnState) = [iota](https://pkg.go.dev/builtin#iota)

	// StateActive represents a connection that has read 1 or more
	// bytes of a request. The Server.ConnState hook for
	// StateActive fires before the request has entered a handler
	// and doesn't fire again until the request has been
	// handled. After the request is handled, the state
	// transitions to StateClosed, StateHijacked, or StateIdle.
	// For HTTP/2, StateActive fires on the transition from zero
	// to one active request, and only transitions away once all
	// active requests are complete. That means that ConnState
	// cannot be used to do per-request work; ConnState only notes
	// the overall state of the connection.
	StateActive

	// StateIdle represents a connection that has finished
	// handling a request and is in the keep-alive state, waiting
	// for a new request. Connections transition from StateIdle
	// to either StateActive or StateClosed.
	StateIdle

	// StateHijacked represents a hijacked connection.
	// This is a terminal state. It does not transition to StateClosed.
	StateHijacked

	// StateClosed represents a closed connection.
	// This is a terminal state. Hijacked connections do not
	// transition to StateClosed.
	StateClosed
)

**Review by MacWill20 — COMMENTED** [review]
good

**Review by MacWill20 — COMMENTED** [review]
http. need new variable to call

**Review by pouriya73 — COMMENTED** [review]
resp , image/jpeg and image/jpg

**Comment by pouriya73** [comment]
> Co-authored-by: Pouriya [nlp.developer.c@gmail.com](mailto:nlp.developer.c@gmail.com)

**Pull request merged**
